// This file was generated by Antigrav based on the requested lib/firebase_options.dart.
// Adapted for React Native/Expo project.

import { Platform } from 'react-native';

/**
 * Default [FirebaseOptions] for use with your [FirebaseApp].
 *
 * This file contains configuration values for each platform (Android, iOS, and Web).
 */
export const FirebaseOptions = {
  android: {
    apiKey: "AIzaSyDt5cpkYnuA1NaRl5pLuiTZxiSqJkiYp_I",
    appId: "1:692757472992:android:78731bd0f106086e339285",
    messagingSenderId: "692757472992",
    projectId: "longeviclinics-prod-543210",
    storageBucket: "longeviclinics-prod-543210.firebasestorage.app",
  },
  ios: {
    apiKey: "AIzaSyDGc49xoLgdSnFKZatB2EKNzEWpkybKLJ4",
    appId: "1:692757472992:ios:02bbc4416bcce306339285",
    messagingSenderId: "692757472992",
    projectId: "longeviclinics-prod-543210",
    storageBucket: "longeviclinics-prod-543210.firebasestorage.app",
    iosBundleId: "com.longeviclinics.app",
  },
  // We'll use the iOS apiKey as a default for any other potential platforms if needed
  default: {
    apiKey: "AIzaSyDGc49xoLgdSnFKZatB2EKNzEWpkybKLJ4",
    appId: "1:692757472992:ios:02bbc4416bcce306339285",
    messagingSenderId: "692757472992",
    projectId: "longeviclinics-prod-543210",
    storageBucket: "longeviclinics-prod-543210.firebasestorage.app",
  }
};

/**
 * Get current platform options
 */
export const currentPlatformOptions = () => {
  if (Platform.OS === 'ios') return FirebaseOptions.ios;
  if (Platform.OS === 'android') return FirebaseOptions.android;
  return FirebaseOptions.default;
};

export default FirebaseOptions;
